### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by dyarochewsky** [wspr-ncsu/visiblev8#8]
Hi, do you have any insight on this error? Getting it on checkout phase

```
Traceback (most recent call last):
  File "./visiblev8/builder/tool.py", line 461, in <module>
    main(sys.argv)
  File "./visiblev8/builder/tool.py", line 455, in main
    args.handler(args)
  File "./visiblev8/builder/tool.py", line 181, in do_checkout
    builder_image = get_builder_image(args)
  File "./visiblev8/builder/tool.py", line 155, in get_builder_image
    docker_run_builder(cname, BUILDER_BASE_IMAGE, "/setup/entry.sh", commit, setup_mount=setup_dir, work_mount=args.root, privileged=args.privileged_docker_run)
  File "./visiblev8/builder/tool.py", line 125, in docker_run_builder
    subprocess.check_call(docker_args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'builder-tool-provision-35938', '-v', '/root/wd:/work', '-e', 'WORKSPACE=/work', '-v', '/root/visiblev8/builder/resources/_provision:/setup:ro', '-e', 'SETUP=/setup', '-w', '/setup', 'ubuntu:xenial', './entry.sh', '5afa96dadfe803e8a058d6ede0c9c3987405b8d8']' returned non-zero exit status 1.
```

**Comment by dyarochewsky** [comment]
This is what I get when I run the docker command manually:
```
....
Adding debian:ePKI_Root_Certification_Authority.pem
Adding debian:emSign_ECC_Root_CA_-_C3.pem
Adding debian:emSign_ECC_Root_CA_-_G3.pem
Adding debian:emSign_Root_CA_-_C1.pem
Adding debian:emSign_Root_CA_-_G1.pem
done.
done.
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
useradd: UID 0 is not unique
builder ALL=(ALL:ALL) NOPASSWD:ALL
No passwd entry for user 'builder'
```

and an empty $WD directory at the end

**Comment by mHassan11** [comment]
Hey, I am facing the similar issue. How did you resolve this?

**Comment by yarochewsky** [comment]
Run with an unprivileged user

**Comment by yarochewsky** [comment]
No, host machine
